### ISSUE TITLE
Style prop optimization

### ISSUE THREAD

**Issue by donjerick** [lotosbin/react-native-pin-input#12]
Getting `TypeError: In this environment the sources for assign MUST be an object.This error is a performance optimization and not spec compliant`.

Reason:

> style={{
>         padding: 2,
>         margin: 2,
>         borderColor: 'gray',
>         borderWidth: 1,
>         width: 30,
>         height: 30,
>         textAlign: 'center',
>         ...this.props.pinItemStyle
> }}

Suggested change in index.php :

> style={ StyleSheet.flatten([
>       {padding: 2,
>       margin: 2,
>       borderColor: 'gray',
>       borderWidth: 1,
>       width: 30,
>       height: 30,
>       textAlign: 'center'}
>       , this.props.pinItemStyle
> ])}

**Comment by lotosbin** [comment]
@donjerick Thanks!
