### ISSUE TITLE
'onKeyPress' not working on Android

### ISSUE THREAD

**Issue by b-asaf** [lotosbin/react-native-pin-input#16]
@lotosbin Thanks for your in reply issue #15 but even after updating my package to 1.2.10 I still can't listen to 'onKeyPress' event on Android.

It seems that 'onKeyPress' event does not fire on Android.
In android keyboard action handling is done via 'onKeyUp' or 'onKeydown', taken from [Handling Keyboard Actions](https://developer.android.com/training/keyboard-input/commands.html)

Another option is to use onChangeText prop for Android and iOS.

Maybe the pull request #14 written by @appjitsu a possible solution, I am not sure its working on both platforms?

**Comment by lotosbin** [comment]
#14 was merged, version is 1.3.0

**Comment by lotosbin** [comment]
https://github.com/facebook/react-native/pull/14720

**Comment by lotosbin** [comment]
https://github.com/facebook/react-native/issues/8330

**Comment by lotosbin** [comment]
https://react-native.canny.io/feature-requests/p/keyup-and-keydown-listener-
