### ISSUE TITLE
style issues

### ISSUE THREAD

**Issue by b-asaf** [lotosbin/react-native-pin-input#18]
Hi,

I am encountering 2 styling issues:

1.  how can I style the blinker that indicate the location that is currently in focus.
2.  how can reduce the space between the pin inputs location?

Thanks

**Comment by lotosbin** [comment]
2.how can reduce the space between the pin inputs location?
I add  prop style to fix issues 2.(version 1.3.1)
```jsx
<PinInput
                    style={{justifyContent: 'space-between', alignSelf: 'stretch'}}
```
this style will merge to 
```jsx index.js
  <View style={StyleSheet.flatten([styles.container, this.props.style])}>
```

1.how can I style the blinker that indicate the location that is currently in focus.

you can use pinItemStyle to set PinItem TextInput's style, I don't know how to set it blinker, it depends on ReactNative's TextInput style.
```
  <PinInput
                    style={{justifyContent: 'space-between', alignSelf: 'stretch'}}
                    ref={(input) => {
                        this.pin = input;
                    }}
                    text=""
                    pinLength={4}
                    pinItemStyle={{width: 50, height: 50, borderTopWidth: 0, borderLeftWidth: 0, borderRightWidth: 0, borderBottomWidth: 2, borderColor: 'green'}}
```

**Comment by lotosbin** [comment]
@assafb81

**Comment by b-asaf** [comment]
@lotosbin - another style issue that is actually prop issue #5 or pull-request #19 

I think this issue can be closed.
the blinker/cursor can be styled using [selectioncolor](https://facebook.github.io/react-native/docs/textinput.html#selectioncolor)
