### ISSUE TITLE
Set Initial Pin

### ISSUE THREAD

**Issue by strataga** [lotosbin/react-native-pin-input#5]
How can you set the initial value of the pin?

**Comment by lotosbin** [comment]
Pin Input is usually used to verify,
What scene requires an initial value？

**Comment by strataga** [comment]
My requirement is for a new user account wizard where they can go forward and back in the process. Each step of the wizard has a different piece of the users information such as name, date of birth etc. I have been using your module for the pin on one of the steps, but I need to be to put a initial value on the pin if the user goes back to it. Like the other controls, like an input text field, I have to save the state and then supply that state as the default value. Make sense?

**Comment by lotosbin** [comment]
version 1.2.1 add methods
## method
- setPin

```javascript
this.refs.pin.setPin('123456')
```
- getPin
```javascript
const pin = this.refs.pin.getPin()
```
- clearPin
```javascript
this.refs.pin.clearPin()
```

**Comment by strataga** [comment]
value={this.state.pin} would be nice to have.

Also, ability to turn off auto focus.

**Comment by strataga** [comment]
ref={(input) => { this.pin = input; }}
this.pin.setPin(this.state.pin); <== this.pin is undefined

this.refs is deprecated

**Comment by lotosbin** [comment]
version 1.2.2
add init value,
autoFocus prop,
focusPin method

**Comment by strataga** [comment]
Thanks. The new features help me out a lot.

Given the code below, how would I use focusPin()? I'm using **ref={input => this.pin === input}** to hold a reference.

```
<Form style={styles.form}>
  <Item stackedLabel>
    <Label>Email</Label>
    <Input
      value={this.state.username}
      autoCorrect={false}
      returnKeyType="next"
      autoCapitalize="none"
      keyboardType="email-address"
      enablesReturnKeyAutomatically
      onChangeText={(text) => {
        this.setState({ username: text });
      }}
      onSubmitEditing={() => {
        this.pin.focusPin();
      }}
    />
  </Item>
  <PinInput
    ref={input => this.pin === input}
    text=""
    pinLength={4}
    pinItemStyle={{ width: 50, height: 50, borderWidth: 0, borderBottomWidth: 1 }}
    pinItemProps={{ keyboardType: 'number-pad' }}
    onPinCompleted={(pin) => {
      this.setState({ password: pin });
    }}
    containerStyle={{ backgroundColor: 'transparent' }}
    containerPinStyle={{
      flexDirection: 'row',
      justifyContent: 'space-around',
      alignItems: 'center',
      marginTop: 20,
    }}
  />
...
```

**Comment by lotosbin** [comment]
if autoFocus is false,  clearPin/setPin  will not focus automated.
if need focus,
use `this.pin.focusPin(0)`(this.pin is ref)

**Comment by strataga** [comment]
this.pin is undefined in my use case.

**Comment by strataga** [comment]
Setting **returnKeyType** doesn't appear to work.

`pinItemProps={{ keyboardType: 'number-pad', returnKeyType: 'done' }}`

![screen shot 2017-09-18 at 4 14 22 am](https://user-images.githubusercontent.com/10903600/30535409-e1c2ecf8-9c27-11e7-97ea-2befa366a32b.png)

**Comment by lotosbin** [comment]
should
`ref={input => this.pin = input}`
not
`ref={input => this.pin === input}`

**Comment by strataga** [comment]
OMG...

Did I really just do that?! I'm so ashamed!

![picard_facepalm](https://user-images.githubusercontent.com/10903600/30536172-6c9409dc-9c2a-11e7-9e66-4bcbf54b9edc.jpg)

Everything works great! Thanks for your help!

**Comment by lotosbin** [comment]
about returnKeyType
https://github.com/facebook/react-native/issues/11739

**Comment by strataga** [comment]
I'm using it on another screen for the dob year input.

![screen shot 2017-09-18 at 4 36 14 am](https://user-images.githubusercontent.com/10903600/30536318-f928d706-9c2a-11e7-83c0-bfcd5a9ecc10.png)

```
<Item stackedLabel>
  <Label>Year</Label>
  <Input
    ref={(input) => { this.dobYear = input; }}
    value={this.state.dobYear}
    autoCorrect={false}
    keyboardType="number-pad"
    maxLength={2}
    enablesReturnKeyAutomatically
    returnKeyType="done"
    onChangeText={(text) => {
      this.setState({ dobYear: text }, instance.forceUpdate());
    }}
    onSubmitEditing={() => {
      this.checkDOB();
    }}
    onBlur={() => {
      this.checkDOB();
    }}
  />
</Item>
```

**Comment by lotosbin** [comment]
you can use onPinCompleted props,
```
<PinInput
     onPinCompleted={(pin)=>{
	//some code
    }}
>
</PinInput>
```

**Comment by strataga** [comment]
I also need the ability to have **secureTextEntry** on the input fields.

**Comment by lotosbin** [comment]
need a better way to expose pin item props.

v1.2.3 add pinItemProps support returnKeyType secureTextEntry

**Comment by lotosbin** [comment]
#6

**Comment by strataga** [comment]
The new pinItemProps support works well. Great job!

**Comment by b-asaf** [comment]
@appjitsu & @lotosbin 
Can you expose `underlineColorAndroid` prop (only for **Android**) so I can hide the black line and see only the white bottom border:
![image](https://user-images.githubusercontent.com/28925534/35043913-0bf5307a-fb97-11e7-8e56-9d426534cdda.png)

this is my code:

```
<Input
    ref={(code) => {
        this.regimenCode = code;
    }}
    pinLength={6}
    autoFocus
    text=""
    placeholder=" "
    pinItemProps={{keyboardType: 'numeric', underlineColorAndroid: 'transparent'}}
    pinItemStyle={styles.input}
    onPinEntered={this.handePinEntered}
/>

```

I saw in the code that only 3 text input props are addressed:
![image](https://user-images.githubusercontent.com/28925534/35043973-444d7c84-fb97-11e7-85d6-7856403d8590.png)

I added this line to the index file of the package, under `secureTextEntry` and it did the trick and checked it on iOS and Android devices:
`underlineColorAndroid={(this.props.pinItemProps || {}).underlineColorAndroid || undefined}`

see pull-request #19
