### ISSUE TITLE
Going back to previous pin field

### ISSUE THREAD

**Issue by strataga** [lotosbin/react-native-pin-input#7]
How would you programmatically go back to the previous field input when the keyboard back button is pressed (the one in the bottom right corner)?

![screen shot 2017-10-10 at 7 29 40 am](https://user-images.githubusercontent.com/10903600/31386574-cf93e11a-ad8c-11e7-8e83-81690debbd72.png)

**Comment by timscott** [comment]
I think should be the default behavior. When a digit input is focussed and there is a digit, the first back press should delete the digit, the next should go back to the prior digit input.

**Comment by lotosbin** [comment]
There is no onKeyPress on android,
so I don't know how to implement this on android.

**Comment by strataga** [comment]
This is working in the newest version.
