### ISSUE TITLE
Option for pristine fields not to have the "dot" if the fields are secure text

### ISSUE THREAD

**Issue by strataga** [lotosbin/react-native-pin-input#8]
![screen shot 2017-10-10 at 9 00 19 am](https://user-images.githubusercontent.com/10903600/31390438-82a93564-ad99-11e7-853e-943965b253cc.png)

**Comment by strataga** [comment]
Thanks for the update. Is there any way to remove the dash? My client wants nothing in the fields if they are pristine.

![screen shot 2017-10-17 at 4 06 30 am](https://user-images.githubusercontent.com/10903600/31656230-9915e2f0-b2f0-11e7-9af1-200a098a849f.png)

**Comment by lotosbin** [comment]
@appjitsu you can set placeHolder to space.but there is still a space character.
```
 <PinInput
              placeHolder={' '}
              ...
```
pristine pin value is placeHolder.
if the first pin is 1, and fourth pin is 4,
if placeHolder is ' ', the result is '1  4',
if placeHolder is '-',result is '1--4'.
and must have a placeHolder,default is '-'

**Comment by strataga** [comment]
It's not working for me.

"react-native-pin-input": "^1.2.5"

```
<PinInput
  ref={(input) => { this.pin = input; }}
  text=""
  pinLength={4}
  pinItemStyle={{ width: 50, height: 50, borderWidth: 0, borderBottomWidth: 1 }}
  pinItemProps={{ keyboardType: 'number-pad', returnKeyType: 'done', secureTextEntry: true }}
  placeholder={' '}
  onPinCompleted={(pin) => {
    this.setState({ password: pin });
    Keyboard.dismiss();
  }}
  containerStyle={{ backgroundColor: 'transparent' }}
  containerPinStyle={{
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    marginTop: 20,
  }}
/>
```

**Comment by lotosbin** [comment]
@appjitsu  my mistake, should be **placeholder** , not **placeHolder**

**Comment by strataga** [comment]
I can confirm that this works. Thanks!
