### ISSUE TITLE
Values Displayed Do Not Match State

### ISSUE THREAD

**Issue by timscott** [lotosbin/react-native-pin-input#9]
Steps to reproduce:

1. In a 4-digit pin enter [9] [8] [7] [6]
2. In the `onPinCompleted` check the ref and see that `state.pins` is `["9", "8", "7", "6"]`
3. Tap on some digit . We'll use the second digit as the example. The `8` disappears.
4. Tap on the last digit. The `6` disappears.
5. Type `6` again.
6. In the `onPinCompleted` check the ref and see that `state.pins` is `["9", "8", "7", "6"]`

So the control shows [9] [_] [7] [6], but the values in state do not match what is displayed.

Whenever a character is erased from an input, the state should be eagerly  updated.

**Comment by lotosbin** [comment]
@timscott new version fixed this bug.

**Comment by timscott** [comment]
One thing is a little quirky. Let's say I type `[9] [8] [7] [6]`. Then I realize the first digit is wrong. So I tap on that and change it to `[0]`. The focus moves to the second digit and clears it. As a result, you have to type the whole code again.

Not a deal breaker, but how about this. Whenever you focus a box that has a character (auto or manual), instead of clearing the digit, select it. That way you can still over type it with one press and  advancing will not erase previously entered digits.
